apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.name }}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: {{.Values.acme.server}}
    privateKeySecretRef:
      name: {{.Values.acme.privateKeySecretRef.name}}
    solvers:
    - selector:
        dnsZones:
          {{ toYaml .Values.solvers.dnsZones }}
      dns01:
        route53:
          region: {{ .Values.solvers.dns01.route53.region }}
          {{- if .Values.solvers.dns01.route53.hostedZoneId }}
          hostedZoneId: {{ .Values.solvers.dns01.route53.hostedZoneId }}
          {{- end }}
          accessKeyID: {{ .Values.solvers.dns01.route53.accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ .Values.solvers.dns01.route53.secretAccessKeySecretRef.name }}
            key: {{ .Values.solvers.dns01.route53.secretAccessKeySecretRef.key }}

