apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.name }}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: {{.Values.acme.server}}
    privateKeySecretRef:
      name: {{.Values.acme.privateKeySecretRef.name}}
    solvers:
    # this solver handles example.org challenges
    # and uses explicit credentials
    - selector:
        dnsZones:
          {{ toYaml .Values.solvers.dnsZones }}
      dns01:
        route53:
          region: {{.Values.solvers.dns01.route53.region }}
          accessKeyID: {{ .Values.solvers.dns01.route53.accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ .Values.solvers.dns01.route53.secretAccessKeySecretRef.name }}
            key: {{ .Values.solvers.dns01.route53.secretAccessKeySecretRef.key }}
          # you can also assume a role with these credentials
          #role: arn:aws:iam::YYYYYYYYYYYY:role/dns-manager