apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.name }}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: {{.Values.acme.server}}
    privateKeySecretRef:
      name: {{.Values.acme.privateKeySecretRef.name}}
    solvers:
    - selector:
        dnsZones:
          {{ toYaml .Values.solvers.dnsZones }}
      dns01:
        route53:
          {{- with $.Values.solvers.dns01.route53 }}
          region: {{- .region }}
          {{- if .hostedZoneId }}
          hostedZoneId: {{- .hostedZoneId }}
          {{- end }}
          accessKeyID: {{ .accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ .secretAccessKeySecretRef.name }}
            key: {{ .secretAccessKeySecretRef.key }}
          {{- end }}