apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.name }}
spec:
  acme:
    email: {{.Values.acme.email}}
    server: {{.Values.acme.server}}
    privateKeySecretRef:
      name: {{.Values.acme.privateKeySecretRef.name}}
    solvers:
    - selector:
        dnsZones:
          {{ toYaml .Values.solvers.dnsZones }}
      dns01:
        {{- if $.Values.solvers.dns01.route53 }}
        route53:
          {{- with $.Values.solvers.dns01.route53 }}
          {{ toYaml . | indent 4 }}
          {{- end }}
          {{- end }}