name: letsencrypt-issuer
acme:
  email: some-email@example.com
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: letsencrypt-issuer-key
solvers:
  dnsZones:
  - "example.org"
  dns01:
    route53:
      region: us-east-1
      accessKeyID: AKIAIOSFODNN7EXAMPLE
      hostedZoneId:
      secretAccessKeySecretRef:
        name: prod-route53-credentials-secret
        key: secret-access-key
